<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="JWT" Version="11.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="2.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.2.7" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.1" />
    <PackageReference Include="System.Collections" Version="4.3.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.9.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mark\Consulta\Arrepentimientos\DAOs\" />
    <Folder Include="Mark\Consulta\Histórico\Controllers\" />
    <Folder Include="Mark\Consulta\Histórico\Interfaces\" />
    <Folder Include="Mark\Consulta\Histórico\Services\" />
    <Folder Include="Mark\Consulta\Informacion\Comentarios\Controllers\" />
    <Folder Include="Mark\Consulta\Informacion\Comentarios\DAOs\" />
    <Folder Include="Mark\Consulta\Informacion\Comentarios\Interfaces\" />
    <Folder Include="Mark\Consulta\Informacion\Comentarios\Services\" />
    <Folder Include="Mark\Consulta\Informacion\Ofrecimientos\Controllers\" />
    <Folder Include="Mark\Consulta\Informacion\Ofrecimientos\DAOs\" />
    <Folder Include="Mark\Consulta\Informacion\Ofrecimientos\Interfaces\" />
    <Folder Include="Mark\Consulta\Informacion\Ofrecimientos\Services\" />
    <Folder Include="Mark\Consulta\Informacion\Busquedas\Controllers\" />
    <Folder Include="Mark\Consulta\Informacion\Busquedas\DAOs\" />
    <Folder Include="Mark\Consulta\Informacion\Busquedas\Interfaces\" />
    <Folder Include="Mark\Consulta\Informacion\Busquedas\Services\" />
    <Folder Include="Mark\Consulta\Informacion\Correos\Controllers\" />
    <Folder Include="Mark\Consulta\Informacion\Correos\DAOs\" />
    <Folder Include="Mark\Consulta\Informacion\Correos\Interfaces\" />
    <Folder Include="Mark\Consulta\Informacion\Correos\Services\" />
    <Folder Include="Mark\Consulta\Informacion\DatosErroneos\Controllers\" />
    <Folder Include="Mark\Consulta\Informacion\DatosErroneos\DAOs\" />
    <Folder Include="Mark\Consulta\Informacion\DatosErroneos\Interfaces\" />
    <Folder Include="Mark\Consulta\Informacion\DatosErroneos\Services\" />
    <Folder Include="Mark\Consulta\Informacion\PagosReportados\Controllers\" />
    <Folder Include="Mark\Consulta\Informacion\PagosReportados\DAOs\" />
    <Folder Include="Mark\Consulta\Informacion\PagosReportados\Interfaces\" />
    <Folder Include="Mark\Consulta\Informacion\PagosReportados\Services\" />
  </ItemGroup>

  

</Project>
