const equivalenciasCartera = {
    1: "American Express",
    2: "Scotian Bank",
    3: "Banamex",
    4: "Santander",
    5: "HSBC",
    6: "Infonavit",
    7: "BBVA Bancomer",
    8: "VW",
    9: "Toyota",
    10: "Sicrea",
    11: "Welcome",
    12: "BMW",
    13: "Nissan",
    14: "Laboratorio",
    15: "STM Financial",
    16: "Su Auto",
    17: "Daimler",
    18: "Pendulum",
    19: "Autofin",
    20: "ELAVON",
    21: "Afirme",
    22: "FinReal",
    23: "Libertad Servicios Financieros",
    24: "Comision Federal De Electricidad",
    25: "MF Amiga",
    26: "Irene",
    27: "Terminaciones Leasing",
    28: "AT&T",
    29: "Toyota AP",
    30: "Inmediauto",
    31: "Soriana",
    32: "Toyota Remanentes",
    33: "AT&T CANCELADA",
    34: "Créditos",
    35: "Credito Nomina",
    36: "Banco Azteca",
    37: "Zendere",
    38: "Sofom Inbursa",
    39: "Inbursa",
    40: "CI Banco Judicial",
    41: "CI Banco ExtraJudicial",
    42: "Fiduciaria",
    43: "Banorte",
    44: "HSBC ATC",
    45: "Tienda Soriana",
    46: "Toyota Legal",
    47: "Santander Seguros",
    48: "Toyota Terminaciones",
    49: "Toyota Leasing",
    50: "Rappi",
    51: "Toyota Administracion",
    52: "Inbound",
    53: "Autocom",
    54: "CITA DE SERVICIO TOYOTA",
    55: "VW BACK OFFICE",
    56: "Banbajio",
    57: "MACROPAY",
    58: "Mercado Crédito",
    59: "Fin Común",
    60: "Unifin",
    61: "PLATA",
    62: "Coppel",
    63: "CREDITAS",
    64: "Cartera Adquirida",
    65: "Didi",
    66: "Audi",
    67: "NU",
    68: "Mercado Digital",
    69: "Demandas Masivas",
    70: "CETELEM",
    71: "Balance Transfer",
    72: "Aherm",
    73: "Banbajio Finados",
};

export default equivalenciasCartera;
